Repository ynput/ayon-applications, pull requests merged in 2024-09, with the labels that each got.

#22 Set applications "tools" being used as info log instead of debug
  client/ayon_applications/utils.py
Labels: enhancement

#12 Add a Debug Shell launcher which allows to launch a terminal into environment of an application
  client/ayon_applications/addon.py
  client/ayon_applications/defs.py
  client/ayon_applications/hooks/prelaunch_shell_windows.py
  client/ayon_applications/icons/terminal.png
  client/ayon_applications/plugins/launcher_actions/debug_terminal.py
  client/ayon_applications/utils.py
  public/icons/terminal.png
  server/applications.json
  server/constants.py
  server/settings.py
Labels: enhancement

#32 Use variant name if label is not filled
  server/applications.json
  server/settings.py
Labels: type: bug

#33 Webactions: Skip disabled applications
  server/actions.py
Labels: type: bug

#35 Icons: Update flame icon
  client/ayon_applications/icons/flame.png
  public/icons/flame.png
Labels: type: maintenance
