Repository ynput/ayon-applications, pull requests merged in 2025-01, with the labels that each got.

#44 Log opening of last workfile was disabled only if `start_last_workfile is False` explicitly
  client/ayon_applications/utils.py
Labels: type: bug

#43 Fill environment variables for farm jobs
  client/ayon_applications/plugins/publish/collect_farm_env_variables.py
Labels: type: enhancement

#45 Add BorisFX Silhouette application
  client/ayon_applications/constants.py
  client/ayon_applications/icons/silhouette.png
  public/icons/silhouette.png
  server/applications.json
  server/settings.py
Labels: type: feature

#50 Add substance designer as applications
  client/ayon_applications/constants.py
  client/ayon_applications/icons/substancedesigner.png
  server/applications.json
  server/settings.py
Labels: type: feature

#52 Substance designer: Define label and icon on server
  public/icons/substancedesigner.png
  server/constants.py
Labels: type: bug

#46 Add BorisFX Mocha Pro
  client/ayon_applications/constants.py
  client/ayon_applications/icons/mochapro.png
  public/icons/mochapro.png
  server/applications.json
  server/constants.py
  server/settings.py
Labels: sponsored, type: feature
