Repository ynput/ayon-applications, pull requests merged in 2025-03, with the labels that each got.

#58 Add Blender 4.4 to defaults
  server/applications.json
Labels: type: enhancement, community

#57 Chore: Use env tools functions from ayon core
  client/ayon_applications/utils.py
Labels: type: enhancement

#59 Chore/add speedtree support
  client/ayon_applications/constants.py
  client/ayon_applications/icons/speedtree.png
  public/icons/speedtree.png
  server/applications.json
  server/constants.py
  server/settings.py
Labels: sponsored, type: feature
