Repository ynput/ayon-applications, pull requests merged in 2025-04, with the labels that each got.

#64 Server icons: Add missing server icon mapping
  client/ayon_applications/constants.py
  server/constants.py
Labels: type: bug

#66 Add Autodesk Maya 2026
  server/applications.json
Labels: type: enhancement

#67 Add Fusion 19 and 20 to defaults
  server/applications.json
Labels: type: enhancement, community

#70 Webactions: Use project settings for applications list
  server/actions.py
Labels: type: bug

#69 Debug terminal: Add check for icon value
  client/ayon_applications/plugins/launcher_actions/debug_terminal.py
Labels: type: bug
