Repository ynput/ayon-applications, pull requests merged in 2025-06, with the labels that each got.

#79 Add 'Environment' JSON validation to settings
  server/settings.py
Labels: type: enhancement, community

#81 Speedtree icon: Use standard PNG format
  client/ayon_applications/icons/speedtree.png
  public/icons/speedtree.png
Labels: type: enhancement

#82 Settings: Refactor `conditionalEnum` -> `conditional_enum`
  server/settings.py
Labels: community, type: maintenance
